var checkers = [
    {row: 1, cell: 2, color: 'white' },
    {row: 1, cell: 2, color: 'white' },
    {row: 1, cell: 2, color: 'white' },
    {row: 1, cell: 2, color: 'white' },
    {row: 2, cell: 2, color: 'white' },
    {row: 2, cell: 2, color: 'white' },
    {row: 2, cell: 2, color: 'white' },
    {row: 2, cell: 2, color: 'white' },
    {row: 3, cell: 2, color: 'white' },
    {row: 3, cell: 2, color: 'white' },
    {row: 3, cell: 2, color: 'white' },
    {row: 3, cell: 2, color: 'white' },
    {row: 6, cell: 2, color: 'black' },
    {row: 6, cell: 2, color: 'black' },
    {row: 6, cell: 2, color: 'black' },
    {row: 6, cell: 2, color: 'black' },
    {row: 7, cell: 2, color: 'black' },
    {row: 7, cell: 2, color: 'black' },
    {row: 7, cell: 2, color: 'black' },
    {row: 7, cell: 2, color: 'black' },
    {row: 8, cell: 2, color: 'black' },
    {row: 8, cell: 2, color: 'black' },
    {row: 8, cell: 2, color: 'black' },
    {row: 8, cell: 2, color: 'black' },
    
]